routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Este metodo cria automaticamente todas as rotas de login/registro e etc
Auth::routes();

Route::get('/', function () {
    return redirect('/home');
});

Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

//Rotas dentro desse grupo usam o middleware auth
//Isso quer dizer que só usuários logados tem permissão de acesso
//Quem não estiver logado é redirecionado para a página de login
Route::group(['middleware' => ['auth']], function () 
{
    //Controllers resource já possuem suas rotas fixas
    //https://laravel.com/docs/5.8/controllers#resource-controllers
	Route::resource('user', 'UserController');
	Route::resource('news', 'NewsController');
    Route::resource('contact', 'ContactController');
});

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    //$fillable ou $guarded são atributos do model para especificar quais campos são protegidos ou livres 
    //para gravação em mass assignment (usando Contact::create($request->all()))
    //https://laravel.com/docs/5.8/eloquent#mass-assignment
    protected $guarded = [];
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

//Model Contact
use App\Contact;
//Para poder usar o Validator
use Illuminate\Support\Facades\Validator;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //Pega todos os contatos do model Contact
        //Para usar esse model, precisamos importar o namespace no topo do código: use App\Contact;
        //Caso queira usar sem importar no topo, o namespace completo da classe deve ser especificado como no exemplo abaixo:
        //$contacts = App\Contact::paginate(10); mas para deixar o código mais limpo, e para concentar todas as dependencias dessa classe em um lugar só, é boa pratica declarar no topo com o use.
        $contacts = Contact::paginate(10);

        return view('contact.index', ['contacts' => $contacts]);

        //Segundo parametro é o array com os dados que vai jogar para a view
        //O array esta sendo declarado já no parametro para salvar espaço, nada impede de criar uma variavel antes como no exemplo abaixo:
        //$data = ['contacts' => $contacts]
        //return view('contact.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //Aqui eu crio algumas variaveis para jogar para o form, para poder aproveitar o mesmo form na criação e edição de contatos
        $data = [
                'form_route'    => route('contact.store'),
                'form_method'   => 'POST',
                'form_title'    => 'Criar Contato'
                ];

        return view('contact.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Validação, se validação falhar, automaticamente redireciona para o formulário com os erros
        $this->validator($request->all())->validate();

        //Cria o contato por mass assignment
        //Pega todos os inputs enviados pelo form e cria automaticamente o Contato
        //Para o Mass Assignment funcionar, tem que ser criado a propriedade $fillable ou $guarded no model especificando os campos que podem ser mass assigned
        if(Contact::create($request->all()))
        {
            $message = 'Contato Criado';  
        }
        else
        {
            $message = 'Falha ao criar contato';
        }

        return back()->with('alerts', $message);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $contact = Contact::FindOrFail($id);
        return view('contact.show', ['contact' => $contact]);
    }

    /**
     * Mostra o form para edição do resource
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $contact = Contact::FindOrFail($id);

        $data = [
                'contact'          => $contact,
                'form_route'    => route('contact.update', ['id' => $contact->id]),
                'form_method'   => 'PUT',
                'form_title'    => 'Editar Contato'
                ];

        return view('contact.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $contact = Contact::FindOrFail($id);

        $data = $request->all();        

        //Validação
        $this->validator($data)->validate();
        
        //Se a validação passar, atualizamos o contato e salvamos
        //Repare que poderiamos atualizar o contato por mass assignment (igual no metodo store) ou pelo metodo abaixo (alterando campo por campo e salvando)
        //aqui estamos fazendo desta forma para demonstrar que as 2 formas são possiveis
        $contact->nome     = $request->input('nome');
        $contact->telefone = $request->input('telefone');
        $contact->email    = $request->input('email');
        $contact->cep      = $request->input('cep');
        $contact->save();

        return back()->with('alerts', 'Contatos Atualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        if($request->filled('ids'))
        {
            $ids = $request->input('ids');

            $deleted_count = Contact::destroy($ids);
            if($deleted_count > 0)
            {
                return redirect('contact')->with('alerts', $deleted_count . ' Contatos deletados');
            }
        }
        else
        {           
            return back()->with('alerts', 'Nenhum registro foi selecionado para remoção.');
        }
        
    }

    protected function validator(array $data)
    {
        //Validação dos campos do formulário
        return Validator::make($data, [
            'nome'      => ['required', 'string', 'max:255'],
            'telefone'  => ['required', 'string', 'max:255'],
            'cep'       => ['required', 'string', 'max:8'],
            'email'     => ['required', 'string', 'email', 'max:255'],
        ]);
    }
}

resources/views/contact/form.blade.php
@extends('layouts.admin')
@section('title', $form_title)

@section('toolbar')
  <button class="btn btn-sm btn-primary" id="salvar"><i data-feather="save"></i> Salvar</button>&nbsp;
  <a href="{{route('contact.index')}}" class="btn btn-sm btn-primary"><i data-feather="arrow-left"></i> Voltar</a>
@endsection

@section('content')
<div class="col-md-12">
    <form action="{{$form_route}}" method="POST" name="contact_form">
      @method($form_method)
      @csrf
      <div class="row">
        <div class="col-md-12 mb-3">
          <label for="nome">Nome</label>
          <input name="nome" type="text" class="form-control" placeholder="" value="{{$contact->nome ?? ''}}" required>
          <div class="invalid-feedback">
            Valid first name is required.
          </div>
        </div>        
      </div>

      <div class="row">
        <div class="col-md-12 mb-3">
          <label for="telefone">Telefone</label>
          <input name="telefone" type="text" class="form-control" placeholder="" value="{{$contact->telefone ?? ''}}" required>
          <div class="invalid-feedback">
            Telefone é obrigatório
          </div>
        </div>        
      </div> 

      <div class="mb-3">
        <label for="email">Email </label>
        <input name="email" type="email" class="form-control" placeholder="you@example.com" value="{{$contact->email ?? ''}}">
        <div class="invalid-feedback">
          Please enter a valid email address for shipping updates.
        </div>
      </div>

      <div class="row">
        <div class="col-md-12 mb-3">
          <label for="cep">CEP</label>
          <input name="cep" type="text" class="form-control" placeholder="" value="{{$contact->cep ?? ''}}" required>
          <div class="invalid-feedback">
            CEP é obrigatório
          </div>
        </div>        
      </div>

      <input type="submit" style="display: none;" />

    </form>
  </div>
</div>
@endsection

@push('scripts')
  <script type="text/javascript">
    $(document).ready(function()
    {

      //Pega elemento input do cep
      let $cep = $('input[name="cep"]');

      //Ao digitar o valor do CEP, roda a cada digito
      $cep.keyup(function()
      {
        //Pega o valor do campo CEP
        let cepVal = $cep.val();
        //Remove espaços
        cepVal = cepVal.replace(" ", "");
        //Remove -
        cepVal = cepVal.replace("-", "");
        //Remove não digitos
        cepVal = cepVal.replace(/\D/, "");
        //Seta o valor substituido no input novamente
        $cep.val(cepVal);
      });

      //Clique no botão Salvar
      $('#salvar').click(function()
      {
        //VALIDAÇÃO CEP
        //Pega o valor cep do input
        let cep = $cep.val();

        //Faz chamada para a API https://viacep.com.br/ com o cep na URL
        $.getJSON("https://viacep.com.br/ws/"+cep+"/json/", function(data)
        {
          if(data)
          {
            //Se retornou dado o CEP eh valido, envia o formulário para salvar Contato
            $('form[name=contact_form]').submit();
          }
        }).fail(function(jqxhr, textStatus, error)
        {
          //Se a API retornar falha, CEP invalido
          alert("CEP "+$cep.val()+" é Invalido.");
        });
      });

    });

  </script>
@endpush

resources/views/contact/index.blade.php
@extends('layouts.admin')
@section('title', 'Listar contatos')

@section('toolbar')
	<a href="{{route('contact.create')}}" class="btn btn-sm btn-primary"><i data-feather="plus-circle"></i> Novo</a>&nbsp;
	<button class="btn btn-sm btn-danger" id="excluir"><i data-feather="trash"></i> Excluir selecionados</button>
@endsection

@section('content')
	@if(!isset($contacts) || count($contacts) <= 0)
		@include('shared.no_results')
	@else
	<form action="{{url('contact/destroy')}}" method="POST" id="contacts">
		@method('DELETE')
		@csrf
		<div class="table-responsive">	
			<table class="table table-striped table-sm">
			  <thead>
			    <tr>
			      <th><input type="checkbox" id="toggle_all"/></th>
			      <th>#</th>
			      <th>Nome</th>
			      <th>E-mail</th>
			      <th>Telefone</th>
			      <th>Cep</th>
			      <th>Criado em</th>
			      <th>Editado em</th>
			      <th>Ações</th>
			    </tr>
			  </thead>
			  <tbody>
			  @foreach($contacts as $contact)
			    <tr>
			      <td><input type="checkbox" name="ids[]" class="ids" value="{{$contact->id}}" /></td>
			      <td>{{$contact->id}}</td>
			      <td>{{$contact->nome}}</td>
			      <td>{{$contact->email}}</td>
			      <td>{{$contact->telefone}}</td>
			      <td>{{$contact->cep}}</td>
			      <td>{{$contact->created_at->format('d/m/Y \\a\\s H:i:s')}}</td>
			      <td>{{$contact->updated_at->format('d/m/Y \\a\\s H:i:s')}}</td>
			      <td>
			      	<a class="btn btn-sm btn-outline-secondary" href="{{route('contact.show', ['id' => $contact->id])}}">Exibir</a>
			      	<a type="button" class="btn btn-sm btn-outline-secondary" href="{{route('contact.edit', ['id' => $contact->id])}}">Editar</a>
			      </td>
			    </tr>
			   @endforeach
			  </tbody>
			</table>
		</div>
		{{$contacts->links()}}
	@endif
@endsection

@push('scripts')
	<script type="text/javascript">
		$(document).ready(function()
		{
			$('#excluir').click(function()
			{
				if(confirm('Esta ação não pode ser desfeita. Excluir registros?'))
				{
					$('#contacts').submit();
				}
			});

			$("#toggle_all").change(function()
			{
				console.log('changed');
				if(this.checked)
				{
					console.log('checked');
					$(':checkbox[class=ids]').prop('checked', this.checked)
				}
				else
				{
					$(':checkbox[class=ids]').prop('checked', '')
				}
			})			
		});

	</script>
@endpush

resources/views/contact/show.blade.php
@extends('layouts.admin')
@section('title', 'Exibir Usuário')

@section('toolbar')
  <a href="{{route('contact.index')}}" class="btn btn-sm btn-primary" id="salvar">Voltar</a>
@endsection

@section('content')
<div class="col-md-12">
      <div class="row">
        <div class="col-md-12 mb-3">
          <label for="firstName">Nome</label>
          <input name="nome" type="text" class="form-control" placeholder="" value="{{$contact->nome ?? ''}}" readonly="readonly">
        </div>        
      </div>

      <div class="mb-3">
        <label for="email">Telefone </label>
        <input name="telefone" type="text" class="form-control" value="{{$contact->telefone ?? ''}}" readonly="readonly">
      </div>

      <div class="mb-3">
        <label for="email">Email </label>
        <input name="email" type="email" class="form-control" value="{{$contact->email ?? ''}}" readonly="readonly">
      </div>

      <div class="mb-3">
        <label for="email">CEP </label>
        <input name="cep" type="text" class="form-control" value="{{$contact->cep ?? ''}}" readonly="readonly">
      </div>

      <div class="mb-3">
        <label for="email">Criado em </label>
        <input name="email" type="text" class="form-control" value="{{$contact->created_at ?? ''}}" readonly="readonly">
      </div>

      <div class="mb-3">
        <label for="email">Modificado em </label>
        <input name="email" type="text" class="form-control" value="{{$contact->updated_at ?? ''}}" readonly="readonly">      
      </div>

  </div>
</div>
@endsection