routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Este metodo cria automaticamente todas as rotas de login/registro e etc
Auth::routes();

Route::get('/', function () {
    return redirect('/home');
});

Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

//Rotas dentro desse grupo usam o middleware auth
//Isso quer dizer que só usuários logados tem permissão de acesso
//Quem não estiver logado é redirecionado para a página de login
Route::group(['middleware' => ['auth']], function () 
{
    //Controllers resource já possuem suas rotas fixas
    //https://laravel.com/docs/5.8/controllers#resource-controllers
	Route::resource('user', 'UserController');
	Route::resource('news', 'NewsController');
    Route::resource('contact', 'ContactController');
});

app/User.php
<?php

namespace App;

use Laravel\Passport\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function news()
    {
        return $this->hasMany('App\News');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rule;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $users = User::paginate(10);
        return view('user.index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [
                'form_route'    => route('user.store'),
                'form_method'   => 'POST',
                'form_title'    => 'Criar Usuário'
                ];

        return view('user.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         //Validação
        $this->validatorCreate($request->all())->validate();
        
        $user = new User;
        $user->name = $request->input('name');
        $user->email = $request->input('email');
        $user->password = Hash::make($request->input('password'));
        $user->save();

        return back()->with('alerts', 'Usuário Criado');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::FindOrFail($id);
        return view('user.show', ['user' => $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {        
        $user = User::FindOrFail($id);

        $data = [
                'user'          => $user,
                'form_route'    => route('user.update', ['id' => $user->id]),
                'form_method'   => 'PUT',
                'form_title'    => 'Editar Usuário'
                ];

        return view('user.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::FindOrFail($id);

        $data = $request->all();

        //Se password for null remove do array para não validar
        if(is_null($data['password']))
        {
            unset($data['password']);
        }
        else
        {
            $user->password = Hash::make($request->input('password'));
        } 

        //Validação
        $this->validatorUpdate($data, $id)->validate();        
        
        $user->name = $request->input('name');
        $user->email = $request->input('email');        
        $user->save();

        return back()->with('alerts', 'Usuário Atualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        if($request->filled('ids'))
        {
            $ids = $request->input('ids');

            $deleted_count = User::destroy($ids);
            if($deleted_count > 0)
            {
                return redirect('user')->with('alerts', $deleted_count . ' usuários deletados');
            }
        }
        else
        {           
            return back()->with('alerts', 'Nenhum registro foi selecionado para remoção.');
        }
        
    }

    protected function validatorUpdate(array $data, $id = null)
    {        
        return Validator::make($data, [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', Rule::unique('users')->ignore($id)],
            'password' => ['sometimes', 'required', 'string', 'min:5', 'confirmed'],
        ]);
    }

    protected function validatorCreate(array $data)
    {        
        return Validator::make($data, [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:6', 'confirmed'],
        ]);
    }

}

resources/views/user/form.blade.php
@extends('layouts.admin')
@section('title', $form_title)

@section('toolbar')
  <button class="btn btn-sm btn-primary" id="salvar"><i data-feather="save"></i> Salvar</button>&nbsp;
  <a href="{{route('user.index')}}" class="btn btn-sm btn-primary"><i data-feather="arrow-left"></i> Voltar</a>
@endsection

@section('content')
<div class="col-md-12">
    <form action="{{$form_route}}" method="POST" name="user_form">
      @method($form_method)
      @csrf
      <div class="row">
        <div class="col-md-12 mb-3">
          <label for="firstName">Nome</label>
          <input name="name" type="text" class="form-control" placeholder="" value="{{$user->name ?? ''}}" required>
          <div class="invalid-feedback">
            Valid first name is required.
          </div>
        </div>        
      </div> 

      <div class="mb-3">
        <label for="email">Email </label>
        <input name="email" type="email" class="form-control" placeholder="you@example.com" value="{{$user->email ?? ''}}">
        <div class="invalid-feedback">
          Please enter a valid email address for shipping updates.
        </div>
      </div>

      <div class="mb-3">
        <label for="email">Senha </label>
        <input name="password" type="password" class="form-control" value="">
        <div class="invalid-feedback">
          Please enter a valid email address for shipping updates.
        </div>
      </div>

      <div class="mb-3">
        <label for="email">Confirmar Senha </label>
        <input name="password_confirmation" type="password" class="form-control" value="">
        <div class="invalid-feedback">
          Please enter a valid email address for shipping updates.
        </div>
      </div>

      <input type="submit" style="display: none;" />

    </form>
  </div>
</div>
@endsection

@push('scripts')
  <script type="text/javascript">
    $(document).ready(function()
    {
      $('#salvar').click(function()
      {        
        $('form[name=user_form]').submit();        
      });      
      
    });

  </script>
@endpush

resources/views/user/index.blade.php
@extends('layouts.admin')
@section('title', 'Listar usuários')

@section('toolbar')
	<a href="{{route('user.create')}}" class="btn btn-sm btn-primary"><i data-feather="plus-circle"></i> Novo</a>&nbsp;
	<button class="btn btn-sm btn-danger" id="excluir"><i data-feather="trash"></i> Excluir selecionados</button>
@endsection

@section('content')
	@if(!isset($users) || count($users) <= 0)
		@include('shared.no_results')
	@else
	<form action="{{url('user/destroy')}}" method="POST" id="users">
		@method('DELETE')
		@csrf
		<div class="table-responsive">	
			<table class="table table-striped table-sm">
			  <thead>
			    <tr>
			      <th><input type="checkbox" id="toggle_all"/></th>
			      <th>#</th>
			      <th>Nome</th>
			      <th>E-mail</th>
			      <th>Criado em</th>
			      <th>Editado em</th>
			      <th>Ações</th>
			    </tr>
			  </thead>
			  <tbody>
			  @foreach($users as $user)
			    <tr>
			      <td><input type="checkbox" name="ids[]" class="ids" value="{{$user->id}}" /></td>
			      <td>{{$user->id}}</td>
			      <td>{{$user->name}}</td>
			      <td>{{$user->email}}</td>
			      <td>{{$user->created_at->format('d/m/Y \\a\\s H:i:s')}}</td>
			      <td>{{$user->updated_at->format('d/m/Y \\a\\s H:i:s')}}</td>
			      <td>
			      	<a class="btn btn-sm btn-outline-secondary" href="{{route('user.show', ['id' => $user->id])}}">Exibir</a>
			      	<a type="button" class="btn btn-sm btn-outline-secondary" href="{{route('user.edit', ['id' => $user->id])}}">Editar</a>
			      </td>
			    </tr>
			   @endforeach
			  </tbody>
			</table>
		</div>
		{{$users->links()}}
	@endif
@endsection

@push('scripts')
	<script type="text/javascript">
		$(document).ready(function()
		{
			$('#excluir').click(function()
			{
				if(confirm('Esta ação não pode ser desfeita. Excluir registros?'))
				{
					$('#users').submit();
				}
			});

			$("#toggle_all").change(function()
			{
				console.log('changed');
				if(this.checked)
				{
					console.log('checked');
					$(':checkbox[class=ids]').prop('checked', this.checked)
				}
				else
				{
					$(':checkbox[class=ids]').prop('checked', '')
				}
			})			
		});

	</script>
@endpush

resources/views/user/show.blade.php
@extends('layouts.admin')
@section('title', 'Exibir Usuário')

@section('toolbar')
  <a href="{{route('user.index')}}" class="btn btn-sm btn-primary" id="salvar">Voltar</a>
@endsection

@section('content')
<div class="col-md-12">
      <div class="row">
        <div class="col-md-12 mb-3">
          <label for="firstName">Nome</label>
          <input name="name" type="text" class="form-control" placeholder="" value="{{$user->name ?? ''}}" readonly="readonly">
        </div>        
      </div> 

      <div class="mb-3">
        <label for="email">Email </label>
        <input name="email" type="email" class="form-control" value="{{$user->email ?? ''}}" readonly="readonly">
      </div>

      <div class="mb-3">
        <label for="email">Criado em </label>
        <input name="email" type="text" class="form-control" value="{{$user->created_at ?? ''}}" readonly="readonly">
      </div>

      <div class="mb-3">
        <label for="email">Modificado em </label>
        <input name="email" type="text" class="form-control" value="{{$user->updated_at ?? ''}}" readonly="readonly">      
      </div>

  </div>
</div>
@endsection