routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Este metodo cria automaticamente todas as rotas de login/registro e etc
Auth::routes();

Route::get('/', function () {
    return redirect('/home');
});

Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

//Rotas dentro desse grupo usam o middleware auth
//Isso quer dizer que só usuários logados tem permissão de acesso
//Quem não estiver logado é redirecionado para a página de login
Route::group(['middleware' => ['auth']], function () 
{
    //Controllers resource já possuem suas rotas fixas
    //https://laravel.com/docs/5.8/controllers#resource-controllers
	Route::resource('user', 'UserController');
	Route::resource('news', 'NewsController');
    Route::resource('contact', 'ContactController');
});

resources/views/shared/alerts.blade.php
@if(session('alerts'))
	<div class="alert alert-warning alert-dismissible fade show" role="alert">
	  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	    <span aria-hidden="true">&times;</span>
	  </button>
	  {{session('alerts')}}
	</div>
@endif

resources/views/shared/errors.blade.php
@if ($errors->any())
	<div class="alert alert-danger alert-dismissible fade show" role="alert">
	  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	    <span aria-hidden="true">&times;</span>
	  </button>
		@foreach ($errors->all() as $error)
		  <li>{{ $error }}</li>
		@endforeach
	</div>
@endif

resources/views/shared/navigation.blade.php
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
  <div class="sidebar-sticky">
    <ul class="nav flex-column">
      <li class="nav-item">
        <a class="nav-link active" href="{{route('home')}}">
          <span data-feather="home"></span>
          Dashboard <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{route('user.index')}}">
          <span data-feather="users"></span>
          Usuários
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{route('news.index')}}">
          <span data-feather="file-text"></span>
          Notícias
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{route('contact.index')}}">
          <span data-feather="users"></span>
          Agenda de Contatos
        </a>
      </li>
    </ul>

    <!--h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Saved reports</span>
      <a class="d-flex align-items-center text-muted" href="#">
        <span data-feather="plus-circle"></span>
      </a>
    </h6>
    <ul class="nav flex-column mb-2">
      <li class="nav-item">
        <a class="nav-link" href="#">
          <span data-feather="file-text"></span>
          Current month
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <span data-feather="file-text"></span>
          Last quarter
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <span data-feather="file-text"></span>
          Social engagement
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <span data-feather="file-text"></span>
          Year-end sale
        </a>
      </li>
    </ul-->
  </div>
</nav>

resources/views/shared/no_results.blade.php
@section('content')
	<p> Nenhum registro retornado </p>
@endsection