routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Este metodo cria automaticamente todas as rotas de login/registro e etc
Auth::routes();

Route::get('/', function () {
    return redirect('/home');
});

Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

//Rotas dentro desse grupo usam o middleware auth
//Isso quer dizer que só usuários logados tem permissão de acesso
//Quem não estiver logado é redirecionado para a página de login
Route::group(['middleware' => ['auth']], function () 
{
    //Controllers resource já possuem suas rotas fixas
    //https://laravel.com/docs/5.8/controllers#resource-controllers
	Route::resource('user', 'UserController');
	Route::resource('news', 'NewsController');
    Route::resource('contact', 'ContactController');
});

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\News;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $news = News::paginate(10);
        return view('news.index', ['news' => $news]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [
                'form_route'    => route('news.store'),
                'form_method'   => 'POST',
                'form_title'    => 'Criar Notícia'
                ];

        return view('news.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         //Validação
        $this->validator($request->all())->validate();
        
        $news = new News;
        $news->title = $request->input('title');
        $news->body = $request->input('body');
        $news->published = $request->input('published') === null ? 0 : 1;
        \Auth::user()->news()->save($news);        

        return back()->with('alerts', 'Notícia Criada');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $news = News::FindOrFail($id);
        return view('news.show', ['news' => $news]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {        
        $news = News::FindOrFail($id);

        $data = [
                'news'          => $news,
                'form_route'    => route('news.update', ['id' => $news->id]),
                'form_method'   => 'PUT',
                'form_title'    => 'Editar Notícia'
                ];

        return view('news.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $news = News::FindOrFail($id);

        $data = $request->all();
        

        //Validação
        $this->validator($data)->validate();        
        $news->title = $request->input('title');
        $news->body = $request->input('body');
        $news->published = $request->input('published') === null ? 0 : 1;
        $news->save();

        return back()->with('alerts', 'Notícia Atualizada');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        if($request->filled('ids'))
        {
            $ids = $request->input('ids');

            $deleted_count = News::destroy($ids);
            if($deleted_count > 0)
            {
                return redirect('news')->with('alerts', $deleted_count . ' notícias deletadas');
            }
        }
        else
        {           
            return back()->with('alerts', 'Nenhum registro foi selecionado para remoção.');
        }
        
    }

    protected function validator(array $data)
    {        
        return Validator::make($data, [
            'title' => ['required', 'string', 'max:255'],
            'body' => ['required', 'string']            
        ]);
    }
    
}

resources/views/news/form.blade.php
@extends('layouts.admin')
@section('title', $form_title)

@section('toolbar')
  <button class="btn btn-sm btn-primary" id="salvar"><i data-feather="save"></i> Salvar</button>&nbsp;
  <a href="{{route('news.index')}}" class="btn btn-sm btn-primary"><i data-feather="arrow-left"></i> Voltar</a>
@endsection

@section('content')
<div class="col-md-12">
    <form action="{{$form_route}}" method="POST" name="news_form">
      @method($form_method)
      @csrf
      <div class="row">
        <div class="col-md-12 mb-3">
          <label for="title">Titulo</label>
          <input name="title" type="text" class="form-control" placeholder="" value="{{$news->title ?? ''}}" required>          
        </div>        
      </div> 

      <div class="mb-3">
        <label for="body">Corpo da Notícia </label>        
        <textarea name="body" class="form-control text-editor" rows="5">{{$news->body ?? ''}}</textarea>        
      </div>

      <div class="checkbox">
        <input name="published" type="checkbox" value="1" @if(isset($news->published)) {{$news->published == 1 ? 'checked' : ''}} @endif>
        <label>Publicado</label>
      </div>      

      

      <input type="submit" style="display: none;" />

    </form>
  </div>
</div>
@endsection

@push('scripts')  

  <script type="text/javascript">
    $(document).ready(function()
    {
      $('#salvar').click(function()
      {        
        $('form[name=news_form]').submit();        
      });      
      
    });
  </script>

  //TinyMCE
  <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
  <script>
  var editor_config = {
    path_absolute : "/",
    selector: "textarea.text-editor",
    plugins: [
      "advlist autolink lists link image charmap print preview hr anchor pagebreak",
      "searchreplace wordcount visualblocks visualchars code fullscreen",
      "insertdatetime media nonbreaking save table contextmenu directionality",
      "emoticons template paste textcolor colorpicker textpattern"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
    relative_urls: false,
    file_browser_callback : function(field_name, url, type, win) {
      var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
      var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

      var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
      if (type == 'image') {
        cmsURL = cmsURL + "&type=Images";
      } else {
        cmsURL = cmsURL + "&type=Files";
      }

      tinyMCE.activeEditor.windowManager.open({
        file : cmsURL,
        title : 'Filemanager',
        width : x * 0.8,
        height : y * 0.8,
        resizable : "yes",
        close_previous : "no"
      });
    }
  };

  tinymce.init(editor_config);
</script>
@endpush

resources/views/news/index.blade.php
@extends('layouts.admin')
@section('title', 'Listar Notícias')

@section('toolbar')
	<a href="{{route('news.create')}}" class="btn btn-sm btn-primary"><i data-feather="plus-circle"></i> Novo</a>&nbsp;
	<button class="btn btn-sm btn-danger" id="excluir"><i data-feather="trash"></i> Excluir selecionados</button>
@endsection

@section('content')
	@if(!isset($news) || count($news) <= 0)
		@include('shared.no_results')
	@else
	<form action="{{url('news/destroy')}}" method="POST" id="users">
		@method('DELETE')
		@csrf
		<div class="table-responsive">	
			<table class="table table-striped table-sm">
			  <thead>
			    <tr>
			      <th><input type="checkbox" id="toggle_all"/></th>
			      <th>#</th>
			      <th>Titulo</th>
			      <th>Autor</th>
			      <th>Criado em</th>
			      <th>Editado em</th>
			      <th>Publicada</th>
			      <th>Ações</th>
			    </tr>
			  </thead>
			  <tbody>
			  @foreach($news as $n)
			    <tr>
			      <td><input type="checkbox" name="ids[]" class="ids" value="{{$n->id}}" /></td>
			      <td>{{$n->id}}</td>
			      <td>{{$n->title}}</td>
			      <td>{{$n->user->name}}</td>
			      <td>{{$n->created_at->format('d/m/Y \\a\\s H:i:s')}}</td>
			      <td>{{$n->updated_at->format('d/m/Y \\a\\s H:i:s')}}</td>
			      <td>{{$n->published == 1 ? 'Sim' : 'Não'}}</td>
			      <td>
			      	<a class="btn btn-sm btn-outline-secondary" href="{{route('news.show', ['id' => $n->id])}}">Exibir</a>
			      	<a type="button" class="btn btn-sm btn-outline-secondary" href="{{route('news.edit', ['id' => $n->id])}}">Editar</a>
			      </td>
			    </tr>
			   @endforeach
			  </tbody>
			</table>
		</div>
		{{$news->links()}}
	@endif
@endsection

@push('scripts')
	<script type="text/javascript">
		$(document).ready(function()
		{
			$('#excluir').click(function()
			{
				if(confirm('Esta ação não pode ser desfeita. Excluir registros?'))
				{
					$('#users').submit();
				}
			});

			$("#toggle_all").change(function()
			{
				console.log('changed');
				if(this.checked)
				{
					console.log('checked');
					$(':checkbox[class=ids]').prop('checked', this.checked)
				}
				else
				{
					$(':checkbox[class=ids]').prop('checked', '')
				}
			})			
		});

	</script>
@endpush

resources/views/news/show.blade.php
@extends('layouts.admin')
@section('title', 'Exibir Notícia')

@section('toolbar')
  <a href="{{route('news.index')}}" class="btn btn-sm btn-primary"><i data-feather="arrow-left"></i> Voltar</a>
@endsection

@section('content')
<div class="col-md-12">
      <div class="row">
        <div class="col-md-12 mb-3">
          <label for="title">Titulo</label>
          <input name="title" type="text" class="form-control" placeholder="" value="{{$news->title ?? ''}}" readonly>          
        </div>        
      </div> 

      <div class="mb-3">
        <label for="body">Corpo da Notícia </label>        
        <textarea name="body" class="form-control text-editor" rows="5" readonly> {{$news->body ?? ''}}</textarea>        
      </div>

      <div class="col-md-12 mb-3">
          <label for="title">Autor</label>
          <input name="title" type="text" class="form-control" placeholder="" value="{{$news->user->name ?? ''}}" readonly>          
      </div> 

      <div class="checkbox">
        <input name="published" type="checkbox" value="1" disabled {{$news->published == 1 ? 'checked' : ''}}>
        <label>Publicado</label>
      </div>

      



  </div>
</div>
@endsection

@push('scripts')

//TinyMCE
  <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
  <script>
  var editor_config = {
    readonly : 1,
    path_absolute : "/",
    selector: "textarea.text-editor",
    plugins: [
      "advlist autolink lists link image charmap print preview hr anchor pagebreak",
      "searchreplace wordcount visualblocks visualchars code fullscreen",
      "insertdatetime media nonbreaking save table contextmenu directionality",
      "emoticons template paste textcolor colorpicker textpattern"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
    relative_urls: false,
    file_browser_callback : function(field_name, url, type, win) {
      var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
      var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

      var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
      if (type == 'image') {
        cmsURL = cmsURL + "&type=Images";
      } else {
        cmsURL = cmsURL + "&type=Files";
      }

      tinyMCE.activeEditor.windowManager.open({
        file : cmsURL,
        title : 'Filemanager',
        width : x * 0.8,
        height : y * 0.8,
        resizable : "yes",
        close_previous : "no"
      });
    }
  };

  tinymce.init(editor_config);
</script>

@endpush